---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600

    - name: ensure curl is present
      apt:
        name: curl
        state: present

    - name: create molecule user
      user:
        name: molecule

  tasks:
    - name: "Include ansible-role-kitty"
      include_role:
        name: "ansible-role-kitty"
      vars:
        ansible_user: molecule
        become_user: molecule
